# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bookbar = QtWidgets.QLineEdit(self.page_2)
        self.bookbar.setText("")
        self.bookbar.setReadOnly(True)
        self.bookbar.setObjectName("bookbar")
        self.horizontalLayout_5.addWidget(self.bookbar)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.b1 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        self.b1.setObjectName("b1")
        self.horizontalLayout_2.addWidget(self.b1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bigtext = QtWidgets.QLabel(Form)
        self.bigtext.setStyleSheet("font: 14pt \"Arial\";")
        self.bigtext.setObjectName("bigtext")
        self.horizontalLayout.addWidget(self.bigtext)
        self.wordprogress = QtWidgets.QLabel(Form)
        self.wordprogress.setStyleSheet("font: 14pt \"Arial\";")
        self.wordprogress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wordprogress.setObjectName("wordprogress")
        self.horizontalLayout.addWidget(self.wordprogress)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setAutoFillBackground(True)
        self.stackedWidget_2.setStyleSheet("font: 10pt \"Arial\";")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.smalltext = QtWidgets.QTextEdit(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.smalltext.sizePolicy().hasHeightForWidth())
        self.smalltext.setSizePolicy(sizePolicy)
        self.smalltext.setStyleSheet("font: 12pt \"Arial\";\n"
"border: inset;")
        self.smalltext.setUndoRedoEnabled(False)
        self.smalltext.setReadOnly(True)
        self.smalltext.setAcceptRichText(False)
        self.smalltext.setObjectName("smalltext")
        self.verticalLayout_2.addWidget(self.smalltext)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.levelselector = QtWidgets.QSpinBox(self.groupBox_3)
        self.levelselector.setMaximum(100)
        self.levelselector.setSingleStep(5)
        self.levelselector.setProperty("value", 40)
        self.levelselector.setObjectName("levelselector")
        self.verticalLayout_5.addWidget(self.levelselector)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setEnabled(True)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setStyleSheet("")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setEnabled(True)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setEnabled(True)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setStyleSheet("")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setEnabled(True)
        self.label_11.setMinimumSize(QtCore.QSize(50, 0))
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setEnabled(True)
        self.label_15.setMinimumSize(QtCore.QSize(50, 0))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setEnabled(True)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_2.setStyleSheet("font: 10pt \"Arial\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sentencesrb = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentencesrb.sizePolicy().hasHeightForWidth())
        self.sentencesrb.setSizePolicy(sizePolicy)
        self.sentencesrb.setChecked(True)
        self.sentencesrb.setObjectName("sentencesrb")
        self.verticalLayout_4.addWidget(self.sentencesrb)
        self.semicolonsrb = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.semicolonsrb.sizePolicy().hasHeightForWidth())
        self.semicolonsrb.setSizePolicy(sizePolicy)
        self.semicolonsrb.setObjectName("semicolonsrb")
        self.verticalLayout_4.addWidget(self.semicolonsrb)
        self.linesrb = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linesrb.sizePolicy().hasHeightForWidth())
        self.linesrb.setSizePolicy(sizePolicy)
        self.linesrb.setObjectName("linesrb")
        self.verticalLayout_4.addWidget(self.linesrb)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.page_4)
        self.groupBox.setStyleSheet("font: 10pt \"Arial\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wordfrontrb = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordfrontrb.sizePolicy().hasHeightForWidth())
        self.wordfrontrb.setSizePolicy(sizePolicy)
        self.wordfrontrb.setChecked(False)
        self.wordfrontrb.setObjectName("wordfrontrb")
        self.verticalLayout_3.addWidget(self.wordfrontrb)
        self.sentencefrontrb = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentencefrontrb.sizePolicy().hasHeightForWidth())
        self.sentencefrontrb.setSizePolicy(sizePolicy)
        self.sentencefrontrb.setChecked(True)
        self.sentencefrontrb.setObjectName("sentencefrontrb")
        self.verticalLayout_3.addWidget(self.sentencefrontrb)
        self.bothrb = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bothrb.sizePolicy().hasHeightForWidth())
        self.bothrb.setSizePolicy(sizePolicy)
        self.bothrb.setObjectName("bothrb")
        self.verticalLayout_3.addWidget(self.bothrb)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.stackedWidget_2.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b4 = QtWidgets.QPushButton(Form)
        self.b4.setObjectName("b4")
        self.horizontalLayout_3.addWidget(self.b4)
        self.b3 = QtWidgets.QPushButton(Form)
        self.b3.setObjectName("b3")
        self.horizontalLayout_3.addWidget(self.b3)
        self.b2 = QtWidgets.QPushButton(Form)
        self.b2.setObjectName("b2")
        self.horizontalLayout_3.addWidget(self.b2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b1.setText(_translate("Form", "B1"))
        self.bigtext.setText(_translate("Form", "Big Text"))
        self.wordprogress.setText(_translate("Form", "23 / 45"))
        self.smalltext.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_3.setTitle(_translate("Form", "Vocabulary Level"))
        self.label_2.setText(_translate("Form", "Imbecile, Bailiff, Postmortem"))
        self.label_5.setText(_translate("Form", "Muon, Scrivener, Symbolist"))
        self.label.setText(_translate("Form", "0"))
        self.label_10.setText(_translate("Form", "Ecotone, Foreshortening, Elephantiasis"))
        self.label_8.setText(_translate("Form", "Transhumanism, Situs, Monetarist"))
        self.label_9.setText(_translate("Form", "100"))
        self.label_6.setText(_translate("Form", "Plebeian, Linearity, Wildebeest"))
        self.label_4.setText(_translate("Form", "40"))
        self.label_7.setText(_translate("Form", "60"))
        self.label_14.setText(_translate("Form", "Examples"))
        self.label_11.setText(_translate("Form", "Level"))
        self.label_15.setText(_translate("Form", "20"))
        self.label_12.setText(_translate("Form", "Regnum, Blunderbuss, Polytechnics"))
        self.label_13.setText(_translate("Form", "80"))
        self.groupBox_2.setTitle(_translate("Form", "Excerpt Type"))
        self.sentencesrb.setText(_translate("Form", "Sentences (for most books)"))
        self.semicolonsrb.setText(_translate("Form", "Semicolons (for loquacious writers)"))
        self.linesrb.setText(_translate("Form", "Lines (for plays and poetry)"))
        self.groupBox.setTitle(_translate("Form", "Card Type"))
        self.wordfrontrb.setText(_translate("Form", "Word → Sentence +  Definition"))
        self.sentencefrontrb.setText(_translate("Form", "Word + Sentence →  Definition"))
        self.bothrb.setText(_translate("Form", "Both"))
        self.b4.setText(_translate("Form", "B4"))
        self.b3.setText(_translate("Form", "B3"))
        self.b2.setText(_translate("Form", "B2"))

